### ISSUE TITLE
The Damage and K/D of the Total Score disappear after v0.5.6 (2017/8/23)

### ISSUE THREAD

**Issue by AaronChern** [anmonite/wows-stats-plus#1]
Hi anmonite, 

The "Damage" and "K/D" of the "Total Score" disappear after v0.5.6 (2017/8/23).

Will you restore them? 

Thank you for you contribution. This tool is really helpful.

**Comment by anmonite** [comment]
Hi, AaronChern.

Thanks for using my app and posting this inquiry.

Right. I have decided to scrap off both "Damage" and "K/D" columns from "Total Score".
Because I wanted to shrink the window size of browser for single screen users, I need to hide several columns from the list table. After my consideration of stats priority order, those two items were dropped.
I think both items of average damage and kill/death rate of player's total score are little bit meaningless to evaluate among all ship types that a player has.

But if users wish it, I can restore those items by improving to append a UI (checkbox etc.) to select display items that user prefer. Anyway I want to add a "Survival rate" column as a ship stats, I will implement that UI in the future :p

**Comment by AaronChern** [comment]
Hi anmonite,
Thank you for your contribution.
I am really looking forward to it.

**Comment by AaronChern** [comment]
Hi anmonite,
For your information, the Chinese translation of "Survival rate" is "存活率".
