### ISSUE TITLE
wows-stats-plus doesn't work from 2018/6/14‧

### ISSUE THREAD

**Issue by AaronChern** [anmonite/wows-stats-plus#11]
Hi @anmonite ,

Wargaming may change the APIs, so this tool cannot show the stats data from 2018/6/14.

Can your check and fix it? 

Thank  you.

**Comment by anmonite** [comment]
I would confirm you that you have already accepted "WARGAMING API TERMS OF USE" related GDPR on Wargaming Developper's site ( https://developers.wargaming.net ) or not?

Since May 25, user who are using XVM tools need to login Wargaming Developper's site and move into "[My Applications](https://developers.wargaming.net/applications)" accept new term of use. If never, user can not use API call from app.

![12f4d990f718f22cae506b099b093a77-520x261](https://user-images.githubusercontent.com/6539674/41460048-58b7443a-70c6-11e8-82b6-36c8d4d84e69.png)

Please confirm this at first.

**Comment by AaronChern** [comment]
After I accept the "WARGAMING API TERMS OF USE", the problem is solved. Thank you.
